/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    brands: Brand;
    products: Product;
    ecatalogues: Ecatalogue;
    enquiries: Enquiry;
    menu: Menu;
    about: About;
    banner: Banner;
    'contact-info': ContactInfo;
    'feature-sections': FeatureSection;
    'product-tools-section': ProductToolsSection;
    'tool-section': ToolSection;
    testimonials: Testimonial;
    'partners-section': PartnersSection;
    'global-network': GlobalNetwork;
    About_Stats: About_Stat;
    cta: Cta;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    ecatalogues: EcataloguesSelect<false> | EcataloguesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    banner: BannerSelect<false> | BannerSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'feature-sections': FeatureSectionsSelect<false> | FeatureSectionsSelect<true>;
    'product-tools-section': ProductToolsSectionSelect<false> | ProductToolsSectionSelect<true>;
    'tool-section': ToolSectionSelect<false> | ToolSectionSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'partners-section': PartnersSectionSelect<false> | PartnersSectionSelect<true>;
    'global-network': GlobalNetworkSelect<false> | GlobalNetworkSelect<true>;
    About_Stats: About_StatsSelect<false> | About_StatsSelect<true>;
    cta: CtaSelect<false> | CtaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    footer: Footer;
  };
  globalsSelect: {
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  images?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  name: string;
  logo?: (string | null) | Media;
  description?: string | null;
  catalogPdf?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (string | null) | Category;
  brand?: string | null;
  images?: (string | Media)[] | null;
  specifications?: string | null;
  catalogPdf?: (string | null) | Media;
  price: number;
  rating?: number | null;
  reviewCount?: number | null;
  isFeatureTool?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecatalogues".
 */
export interface Ecatalogue {
  id: string;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (string | null) | Category;
  products?: (string | Product)[] | null;
  catalogueFile: string | Media;
  coverImage?: (string | null) | Media;
  isActive?: boolean | null;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: string;
  formTitle?: string | null;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  title: string;
  link: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  about: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner".
 */
export interface Banner {
  id: string;
  title: string;
  slug: string;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (string | null) | Media;
  buttons?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  heroFeatures?:
    | {
        title: string;
        description?: string | null;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: string;
  formTitle?: string | null;
  addressIcon?: (string | null) | Media;
  addressLabel?: string | null;
  address?: string | null;
  phoneIcon?: (string | null) | Media;
  phoneLabel?: string | null;
  phone?: string | null;
  emailIcon?: (string | null) | Media;
  emailLabel?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-sections".
 */
export interface FeatureSection {
  id: string;
  /**
   * Give a unique name like homeSection1, homeSection2
   */
  sectionName: string;
  smallTitle?: string | null;
  heading?: string | null;
  highlightWord?: string | null;
  description1?: string | null;
  description2?: string | null;
  buttonText?: string | null;
  buttonLink?: string | null;
  images: {
    topImage: string | Media;
    bottomImage: string | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-tools-section".
 */
export interface ProductToolsSection {
  id: string;
  smallTitle?: string | null;
  heading?: string | null;
  highlightWord?: string | null;
  viewAllText?: string | null;
  viewAllLink?: string | null;
  tools?:
    | {
        image: string | Media;
        title: string;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-section".
 */
export interface ToolSection {
  id: string;
  slug: string;
  smallTitle?: string | null;
  heading?: string | null;
  highlightWord?: string | null;
  viewAllText?: string | null;
  viewAllLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage customer testimonials shown on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  /**
   * Short heading shown at top of the card.
   */
  title: string;
  /**
   * The customer review paragraph.
   */
  review: string;
  /**
   * Star rating from 1 to 5.
   */
  rating: number;
  /**
   * Check this to show card with orange background. Only one should be featured at a time.
   */
  featured?: boolean | null;
  author: {
    /**
     * Display name e.g. "Aaron Finch"
     */
    name: string;
    /**
     * Profile photo of the reviewer.
     */
    avatar: string | Media;
  };
  /**
   * Only published testimonials appear on the site.
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-section".
 */
export interface PartnersSection {
  id: string;
  tag?: string | null;
  title?: string | null;
  highlight?: string | null;
  partners?:
    | {
        name: string;
        description?: string | null;
        logo: string | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-network".
 */
export interface GlobalNetwork {
  id: string;
  tag?: string | null;
  title?: string | null;
  highlight?: string | null;
  mapImage: string | Media;
  locations?:
    | {
        country?: string | null;
        top?: string | null;
        left?: string | null;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        title?: string | null;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "About_Stats".
 */
export interface About_Stat {
  id: string;
  title: string;
  number: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  id: string;
  title: string;
  highlightWord?: string | null;
  description?: string | null;
  primaryButtonText?: string | null;
  primaryButtonLink?: string | null;
  secondaryButtonText?: string | null;
  secondaryButtonLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'ecatalogues';
        value: string | Ecatalogue;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'menu';
        value: string | Menu;
      } | null)
    | ({
        relationTo: 'about';
        value: string | About;
      } | null)
    | ({
        relationTo: 'banner';
        value: string | Banner;
      } | null)
    | ({
        relationTo: 'contact-info';
        value: string | ContactInfo;
      } | null)
    | ({
        relationTo: 'feature-sections';
        value: string | FeatureSection;
      } | null)
    | ({
        relationTo: 'product-tools-section';
        value: string | ProductToolsSection;
      } | null)
    | ({
        relationTo: 'tool-section';
        value: string | ToolSection;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'partners-section';
        value: string | PartnersSection;
      } | null)
    | ({
        relationTo: 'global-network';
        value: string | GlobalNetwork;
      } | null)
    | ({
        relationTo: 'About_Stats';
        value: string | About_Stat;
      } | null)
    | ({
        relationTo: 'cta';
        value: string | Cta;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  images?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  description?: T;
  catalogPdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  category?: T;
  brand?: T;
  images?: T;
  specifications?: T;
  catalogPdf?: T;
  price?: T;
  rating?: T;
  reviewCount?: T;
  isFeatureTool?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ecatalogues_select".
 */
export interface EcataloguesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  products?: T;
  catalogueFile?: T;
  coverImage?: T;
  isActive?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  formTitle?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  title?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  about?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banner_select".
 */
export interface BannerSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  buttons?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  heroFeatures?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  formTitle?: T;
  addressIcon?: T;
  addressLabel?: T;
  address?: T;
  phoneIcon?: T;
  phoneLabel?: T;
  phone?: T;
  emailIcon?: T;
  emailLabel?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-sections_select".
 */
export interface FeatureSectionsSelect<T extends boolean = true> {
  sectionName?: T;
  smallTitle?: T;
  heading?: T;
  highlightWord?: T;
  description1?: T;
  description2?: T;
  buttonText?: T;
  buttonLink?: T;
  images?:
    | T
    | {
        topImage?: T;
        bottomImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-tools-section_select".
 */
export interface ProductToolsSectionSelect<T extends boolean = true> {
  smallTitle?: T;
  heading?: T;
  highlightWord?: T;
  viewAllText?: T;
  viewAllLink?: T;
  tools?:
    | T
    | {
        image?: T;
        title?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-section_select".
 */
export interface ToolSectionSelect<T extends boolean = true> {
  slug?: T;
  smallTitle?: T;
  heading?: T;
  highlightWord?: T;
  viewAllText?: T;
  viewAllLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  title?: T;
  review?: T;
  rating?: T;
  featured?: T;
  author?:
    | T
    | {
        name?: T;
        avatar?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners-section_select".
 */
export interface PartnersSectionSelect<T extends boolean = true> {
  tag?: T;
  title?: T;
  highlight?: T;
  partners?:
    | T
    | {
        name?: T;
        description?: T;
        logo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "global-network_select".
 */
export interface GlobalNetworkSelect<T extends boolean = true> {
  tag?: T;
  title?: T;
  highlight?: T;
  mapImage?: T;
  locations?:
    | T
    | {
        country?: T;
        top?: T;
        left?: T;
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "About_Stats_select".
 */
export interface About_StatsSelect<T extends boolean = true> {
  title?: T;
  number?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta_select".
 */
export interface CtaSelect<T extends boolean = true> {
  title?: T;
  highlightWord?: T;
  description?: T;
  primaryButtonText?: T;
  primaryButtonLink?: T;
  secondaryButtonText?: T;
  secondaryButtonLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  brand: {
    companyName: string;
    description?: string | null;
    socialLinks?:
      | {
          platform: 'facebook' | 'linkedin' | 'instagram' | 'x' | 'youtube' | 'whatsapp';
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  navColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              url: string;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    enabled?: boolean | null;
    tagline?: string | null;
    placeholder?: string | null;
    buttonLabel?: string | null;
    successMessage?: string | null;
  };
  /**
   * Use {{year}} for the current year.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        companyName?: T;
        description?: T;
        socialLinks?:
          | T
          | {
              platform?: T;
              url?: T;
              id?: T;
            };
      };
  navColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        tagline?: T;
        placeholder?: T;
        buttonLabel?: T;
        successMessage?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}