import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Navbar";
import Footer from "@/components/footer/Footer";
import WhatsAppButton from "@/components/common/WhatsappButton";
import { getFooterData } from "@/lib/getFooter";
import { Poppins, Lato} from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});
const lato = Lato({
  subsets: ['latin'],
  weight: ["100", "300", "400", "700"],
  variable: '--font-lato',
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const footerData = {
    brand: {
      companyName: "H.M Traders",
      description:
        "Established in 1998, H. M. Traders has built a strong reputation in retail and trading of industrial tools.",
      socialLinks: [],
    },

    navColumns: [
      {
        heading: "Quick Links",
        links: [
          { label: "Home", url: "/" },
          { label: "About Us", url: "/about" },
          { label: "Products", url: "/products" },
          { label: "E-catalogue", url: "/catalogue" },
          { label: "Contact Us", url: "/contact" },
        ],
      },
      {
        heading: "Products",
        links: [
          { label: "Cutting Tools", url: "/products" },
          { label: "Carbide Tools", url: "/products" },
          { label: "Tool Storage", url: "/products" },
          { label: "Lifting Equipment", url: "/products" },
        ],
      },
    ],

    newsletter: {
      enabled: true,
      tagline:
        "We specialize in HSS cutting tools, carbide tools, tool storage systems and lifting equipment.",
      placeholder: "Enter your email",
      buttonLabel: "Subscribe",
      successMessage: "Thanks for subscribing!",
    },

    copyright: "© {{year}} H.M Traders. All Rights Reserved",
  };
console.log("footerData", footerData); // Debug log
  return (
    <html lang="en">
  <body className={`${poppins.variable} ${lato.variable} layoutBody`}>
    <Header />

    <main className="mainContent">{children}</main>

    <Footer data={footerData} />
  </body>
</html>
  );
}
