import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Navbar";
import Footer from "@/components/footer/Footer";
import WhatsAppButton from "@/components/common/WhatsappButton";
import { getFooterData } from "@/lib/getFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let footerData;
  try {
    footerData = await getFooterData();
  } catch (error) {
    console.error("Failed to fetch footer data:", error);
    footerData = {
      brand: { companyName: "Company Name" },
      navColumns: [],
      newsletter: { enabled: false },
    };
  }

  return (
    <html lang="en">
      <body className={`layoutBody`}>
        <Header />

        <main className="mainContent">{children}</main>
        <Footer data={footerData} />
      </body>
    </html>
  );
}
